stages:
  data_ingestion:
    cmd: python3 src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - artifacts/raw/
  
  model_training:
    cmd: python3 src/model_training.py
    deps:
     - src/model_training.py
     - artifacts/raw/
    outs: 
     - artifacts/models/fasterrcnn.pth
